//
//  SelectInspectionInteractor.swift
//  Inspection
//
//  Created by Thanawat prathumset on 2/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

protocol SelectInspectionBusinessLogic
{
    func comfirmPlace(request: SelectInspection.Default.Request)
    func fetchLocation(request: SelectInspection.Default.Request)
    func fetchPlantLocation(request: SelectInspection.Default.Request)
    
    func setLocationName(request: SelectInspection.Default.Request, location: CLLocation?)
}

protocol SelectInspectionDataStore
{
  //var name: String { get set }
    var defaultSelectReceiveName : PlantResponse? { get set }
    var defaultSelectStoreName : StorageLocationModel? { get set }
    
    var locationList : [StorageLocationModel]? { get set }
    var plantLocationList : [PlantResponse]? { get set }
}

class SelectInspectionInteractor: SelectInspectionBusinessLogic, SelectInspectionDataStore
{
    var defaultSelectReceiveName: PlantResponse?
    var defaultSelectStoreName: StorageLocationModel?
    
  var presenter: SelectInspectionPresentationLogic?
  var worker: SelectInspectionWorker?
  
    var locationList : [StorageLocationModel]?
  
    var workerReceiver : ReceiverCarWorker?
    var plantLocationList : [PlantResponse]?
    
    let fixedRadius = 10.0
  
  // MARK: Do something
    
    func comfirmPlace(request: SelectInspection.Default.Request){
        
        defaultSelectReceiveName = request.selectReceiveName
        defaultSelectStoreName = request.selectStoreName
        
        //set place
        DataController.shared.receiverCarModel.plant = defaultSelectReceiveName?.plant1
        
        DataController.shared.receiverCarModel.receiverPlace = defaultSelectStoreName?.location
        DataController.shared.receiverCarModel.storePlace = defaultSelectStoreName?.location
        
        
        let response = SelectInspection.Default.Response(selectReceiveName: request.selectReceiveName, selectStoreName: request.selectStoreName)
        presenter?.presentTextDisplay(response: response)
    }
    
    func fetchLocation(request: SelectInspection.Default.Request) {
        worker = SelectInspectionWorker()
        worker?.fetchLocation(completion: { [weak self] (response) in
            
            self?.presenter?.presentFetchLocation(response: response)
            self?.locationList = response.storageList
            
            let firstItem = response.storageList?.first
            

            self?.defaultSelectStoreName = firstItem
            

            DataController.shared.receiverCarModel.receiverPlace = firstItem?.location
            DataController.shared.receiverCarModel.storePlace = firstItem?.location
            
            self?.mappingLocationName()
        })
    }

    func fetchPlantLocation(request: SelectInspection.Default.Request) {
        workerReceiver =  ReceiverCarWorker()
        workerReceiver?.getPlantLocation(completion: { [weak self] response in
            
            
            if let error = response.error {
                let response = SelectInspection.Default.Response(error: error)
                self?.presenter?.presentFetchPlantLocation(response: response)
            }else{

                self?.plantLocationList = response.plantLocations
                let firstItem = response.plantLocations?.first
                
                self?.defaultSelectReceiveName = firstItem
                
                DataController.shared.receiverCarModel.plant = firstItem?.plant1
                
                let response = SelectInspection.Default.Response(plantLocationList: response.plantLocations)
                self?.presenter?.presentFetchPlantLocation(response: response)
                
                self?.mappingLocationName()
            }
        })
    }
    
    var locationName:String?
    
    func setLocationName(request: SelectInspection.Default.Request, location: CLLocation?) {
        self.locationName = request.locationName
//        let response = SelectInspection.Default.Response(locationName:locationName)
//        presenter?.presentTextDisplay(response: response)
        mappingLocationName(location: location)
    }
    
    func randomFloatNumber(lower: Float = 0.01,upper: Float = 0.09) -> Float {
        return (Float(arc4random()) / Float(UInt32.max)) * (upper - lower) + lower
    }
    
    func minimumMaximum<T: Comparable>(_ array: [T]) -> (minimum: T, maximum: T)? {
        guard var minimum = array.first else {
            return nil
        }
        var maximum = minimum
        
        // if 'array' has an odd number of items, let 'minimum' or 'maximum' deal with the leftover
        let start = array.count % 2 // 1 if odd, skipping the first element
        for i in stride(from: start, to: array.count, by: 2) {
            let pair = (array[i], array[i+1])
            
            if pair.0 > pair.1 {
                if pair.0 > maximum {
                    maximum = pair.0
                }
                if pair.1 < minimum {
                    minimum = pair.1
                }
            } else {
                if pair.1 > maximum {
                    maximum = pair.1
                }
                if pair.0 < minimum {
                    minimum = pair.0
                }
            }
        }
        
        return (minimum, maximum)
    }

    fileprivate func mappingLocationName(location: CLLocation? = nil){
        guard var locationName = locationName?
                .replacingOccurrences(of: " ", with: "")
                .lowercased()
                .trimWhiteSpace,
              let locationList = locationList,
              let plantLocationList = plantLocationList  else { return }
        
        print("📍LOCATION: \(locationName)")
        /// fix name songkhla = hatyai
        if locationName == "songkhla" {
            locationName = "hatyai"
        }
        
        let plantModel = plantLocationList.filter { model in
             if let name = model.desc_BU?
                 .replacingOccurrences(of: " ", with: "")
                 .lowercased()
                 .trimWhiteSpace,
                (name == locationName) {
                 return true
             }
             return false
         }
        
        let selectModel = locationList.filter { model in
            if let name = model.location?
                .replacingOccurrences(of: " ", with: "")
                .lowercased()
                .trimWhiteSpace,
               (name == locationName) {
                return true
            }
            return false
        }
        
        if let plantItem = plantModel.first,
           let storeItem = selectModel.first {
            
            print("🥕PLANT: \(plantItem.desc_BU ?? "")")
            print("🥕STORE: \(storeItem.location ?? "")")
            
            self.defaultSelectStoreName = storeItem
            self.defaultSelectReceiveName = plantItem
            
            DataController.shared.receiverCarModel.plant = plantItem.plant1
            
            DataController.shared.receiverCarModel.receiverPlace = storeItem.location
            DataController.shared.receiverCarModel.storePlace = storeItem.location
            
            
            let response = SelectInspection.Default.Response(selectReceiveName: plantItem,
                                                             selectStoreName: storeItem)
            presenter?.presentTextDisplay(response: response)
       
        }else{
            print("NOT MATCH")
        }
        
        
        // 114.261278,30.688977 金川
        var newList = [StorageLocationModel]()
        for i in 0..<locationList.count {
            var apiLocationModel = locationList[i]
            
            
            apiLocationModel.lat = NSNumber(value: 30.688977 + randomFloatNumber())
            apiLocationModel.lon = NSNumber(value: 114.261278 + randomFloatNumber())
            print("📍LOCATION-lan-lon: \(apiLocationModel.lat?.doubleValue ?? 0) \(apiLocationModel.lon?.doubleValue ?? 0)")
            newList.append(apiLocationModel)
        }
        
        var rangeLacationList = [StorageLocationModel]()
        var rangeDoubles: Array<Double> = []

        if let gpsLocation = location {
            
            for var apiLocationModel in newList {
                if let lat = apiLocationModel.lat?.doubleValue , let lon = apiLocationModel.lon?.doubleValue {
                    let apiLocation = CLLocation(latitude: lat, longitude: lon)
                    let distance = gpsLocation.distance(from: apiLocation)
                    
                    let radius = (distance/1000).rounded()
                    print(radius, " km")
                    if radius <= fixedRadius {
                        apiLocationModel.distance = radius
                        rangeLacationList.append(apiLocationModel)
                        rangeDoubles.append(radius)
                    }
                    
                }
            }
        }
        
        if rangeLacationList.count > 0 {
            let minLocation = minimumMaximum(rangeLacationList)?.minimum
            print("📍LOCATION--closest \(minLocation?.distance ?? 0)")
            
            let response = SelectInspection.Default.Response(selectReceiveName: nil,selectStoreName: minLocation)
            presenter?.presentTextDisplay(response: response)
       
        }
    }
}
