//
//  SelectInspectionModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 2/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SelectInspection
{
  // MARK: Use cases
  
  enum Default
  {
    struct Request
    {
        var selectReceiveName : PlantResponse?
        var selectStoreName : StorageLocationModel?
        
        var locationName : String?
    }
    struct Response
    {
        var selectReceiveName : PlantResponse?
        var selectStoreName : StorageLocationModel?
        var storageList : [StorageLocationModel]?
        var plantLocationList : [PlantResponse]?
        var error : KErrorMessage?
        var locationName : String?
        var isCanSelect: Bool = false

    }
    struct ViewModel
    {
        var resultTextPlace : NSMutableAttributedString?
        var errorMessage : String?
        var isCanSelect: Bool = false
    }
  }
}
