//
//  GaugeCheckPresenter.swift
//  Inspection
//
//  Created by Thanawat prathumset on 15/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GaugeCheckPresentationLogic
{
  func presentSomething(response: GaugeCheck.Something.Response)
}

class GaugeCheckPresenter: GaugeCheckPresentationLogic
{
  weak var viewController: GaugeCheckDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: GaugeCheck.Something.Response)
  {
    let viewModel = GaugeCheck.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
