//
//  BookInMotorcycle2Router.swift
//  Inspection
//
//  Created by Thanawat Pratumsat on 23/8/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BookInMotorcycle2RoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol BookInMotorcycle2DataPassing
{
  var dataStore: BookInMotorcycle2DataStore? { get }
}

class BookInMotorcycle2Router: NSObject, BookInMotorcycle2RoutingLogic, BookInMotorcycle2DataPassing
{
  weak var viewController: BookInMotorcycle2ViewController?
  var dataStore: BookInMotorcycle2DataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: BookInMotorcycle2ViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: BookInMotorcycle2DataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
