//
//  InspectionListInteractor.swift
//  Inspection
//
//  Created by Thanawat prathumset on 3/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InspectionListBusinessLogic
{
  func doSomething(request: InspectionList.Something.Request)
}

protocol InspectionListDataStore
{
  //var name: String { get set }
}

class InspectionListInteractor: InspectionListBusinessLogic, InspectionListDataStore
{
  var presenter: InspectionListPresentationLogic?
  var worker: InspectionListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: InspectionList.Something.Request)
  {
    worker = InspectionListWorker()
    worker?.doSomeWork()
    
    let response = InspectionList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
