//
//  SignatureModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 8/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Signature
{
  // MARK: Use cases
    enum USER {
        case SENDER
        case RECEIVER
    }
    
  enum Something
  {
    struct Request
    {
        var signatureView : UIView?
    }
    struct Response
    {
        var titleName : String?
        var signatureImage : UIImage?
        var user : USER?
    }
    struct ViewModel
    {
        var titleName : String?
        var signatureImage : UIImage?
        var user : USER?
    }
  }
}
