//
//  ItemPendingListModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 3/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ItemPendingList
{
  // MARK: Use cases
  
    enum TableType {
        case Default
        case NotFound
        case Found
    }
    
  enum Fetch
  {
    struct Request
    {
        var didSelectItem : BookInListResponse?
    }
    struct Response
    {
        var itemList : [BookInListResponse]?
        var tableType : TableType?
        
        var error : KErrorMessage?
    }
    struct ViewModel
    {
        var itemList : [BookInListResponse]?
        var tableType : TableType?
        
        var errorMessage : String?
    }
  }
}
