//
//  ItemPendingListRouter.swift
//  Inspection
//
//  Created by Thanawat prathumset on 3/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ItemPendingListRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeTodescriptionSegue(segue: UIStoryboardSegue?)
    func routeToViewPDF(segue: UIStoryboardSegue?)
    func routeToEditView(segue: UIStoryboardSegue?)
}

protocol ItemPendingListDataPassing
{
  var dataStore: ItemPendingListDataStore? { get }
}

class ItemPendingListRouter: NSObject, ItemPendingListRoutingLogic, ItemPendingListDataPassing
{
  weak var viewController: ItemPendingListViewController?
  var dataStore: ItemPendingListDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}
    
    func routeTodescriptionSegue(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
      }
    }

    func routeToViewPDF(segue: UIStoryboardSegue?) {
        if let segue = segue {
          let destinationVC = segue.destination as! PDFPreviewViewController
          var destinationDS = destinationVC.router!.dataStore!
            passDataToPdfViewer(source: dataStore!, destination: &destinationDS)
        } else {
          let storyboard = UIStoryboard(name: "PDF", bundle: nil)
          let destinationVC = storyboard.instantiateViewController(withIdentifier: "PDFPreviewViewController") as! PDFPreviewViewController
          var destinationDS = destinationVC.router!.dataStore!
            passDataToPdfViewer(source: dataStore!, destination: &destinationDS)
            navigateToPdfViewer(source: viewController!, destination: destinationVC)
        }
    }
    
    func routeToEditView(segue: UIStoryboardSegue?) {
        if let segue = segue {
          let destinationVC = segue.destination as! PickUpCarViewController
          var destinationDS = destinationVC.router!.dataStore!
            passDataToPickUpCar(source: dataStore!, destination: &destinationDS)
        } else {
          let storyboard = UIStoryboard(name: "PickUpCar", bundle: nil)
          let destinationVC = storyboard.instantiateViewController(withIdentifier: "PickUpCarViewController") as! PickUpCarViewController
          var destinationDS = destinationVC.router!.dataStore!
            passDataToPickUpCar(source: dataStore!, destination: &destinationDS)
            navigateToPickUpCar(source: viewController!, destination: destinationVC)
        }
    }
  // MARK: Navigation
  
     
      
      func navigateToDetail(source: ItemPendingListViewController, destination: DetailViewController)
      {
        source.show(destination, sender: nil)
      }
      
      func navigateToPdfViewer(source: ItemPendingListViewController, destination: PDFPreviewViewController)
      {
        source.show(destination, sender: nil)
      }
      
      func navigateToPickUpCar(source: ItemPendingListViewController, destination: PickUpCarViewController)
      {
        source.show(destination, sender: nil)
      }
    
    // MARK: Passing data
    
      
      func passDataToDetail(source: ItemPendingListDataStore, destination: inout DetailDataStore)
      {
        destination.modelBookinList = source.modelBookinList
      }
      
      func passDataToPdfViewer(source: ItemPendingListDataStore, destination: inout PDFPreviewDataStore)
      {
          destination.documentData = source.documentData
        destination.pdfName = source.pdfName
      }
    
      func passDataToPickUpCar(source: ItemPendingListDataStore, destination: inout PickUpCarDataStore)
      {
          //
          
      }
}
