//
//  ModelCodeModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 9/3/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ModelCode
{
  // MARK: Use cases
    enum TableType {
        case Default
        case Found
        case NotFound
    }
    
  enum Something
  {
    struct Request
    {
        var year:String?
        var make:String?
        var model:String?

        var starterYear:Int?
        
        
        var modelCode:String?
        
        var modelCodeTemplate:ModelCodeTemplateModel?
    }
    struct Response
    {
        var tableType : TableType?
        var yearList: [String]?
        var makeList: [MakeCarModel]?
        var modelList: [ModelCarModel]?
        var searchItemList :  [SearchCodeModel]?
        
        var modelCodeTemplateList : [ModelCodeTemplateModel]?
        
        var error : KErrorMessage?
    }
    struct ViewModel
    {
        var yearList: [String]?
        var makeList: [String]?
        var modelList: [String]?
        var searchItemList :  [SearchCodeModel]?
        
        var modelCodeTemplateList : [ModelCodeTemplateModel]?
        
        var errorMessage : String?
        var tableType : TableType?
    }
  }
}
