//
//  CheckCarPresenter.swift
//  Inspection
//
//  Created by Thanawat prathumset on 4/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CheckCarPresentationLogic
{
  func presentSomething(response: CheckCar.Something.Response)
    func presentReceiverDayTimeInspection(response: CheckCar.Something.Response)
}

class CheckCarPresenter: CheckCarPresentationLogic
{
  weak var viewController: CheckCarDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CheckCar.Something.Response)
  {
    let viewModel = CheckCar.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    func presentReceiverDayTimeInspection(response: CheckCar.Something.Response) {
        let viewModel = CheckCar.Something.ViewModel(dayTime: response.dayTime)
        viewController?.displayReceiverDayTimeInspection(viewModel: viewModel)
    }
    
}
