//
//  CheckCarInteractor.swift
//  Inspection
//
//  Created by Thanawat prathumset on 4/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CheckCarBusinessLogic
{
  func doSomething(request: CheckCar.Something.Request)
    func setReceiverDateTimeInspection(request: CheckCar.Something.Request)
}

protocol CheckCarDataStore
{
  //var name: String { get set }
    var currentDate: Date? { get set }
}

class CheckCarInteractor: CheckCarBusinessLogic, CheckCarDataStore
{
  var presenter: CheckCarPresentationLogic?
  var worker: CheckCarWorker?
  //var name: String = ""
    var currentDate: Date?  
  // MARK: Do something
  
  func doSomething(request: CheckCar.Something.Request)
  {
//    worker = CheckCarWorker()
//    worker?.doSomeWork()
    
    let response = CheckCar.Something.Response()
    presenter?.presentSomething(response: response)
  }
    
    func setReceiverDateTimeInspection(request: CheckCar.Something.Request) {
        let date = request.dateInspection ?? Date()
        
        
        currentDate = date

        let day = DateFormatter().dateFormat(from: date, dateFormat: "dd-MM-yyyy")
        let time = DateFormatter().dateFormat(from: date, dateFormat: "HH:mm")
       
        DataController.shared.inspectionCarModel.date = date
        DataController.shared.inspectionCarModel.dayString = day
        DataController.shared.inspectionCarModel.timeString = time
        
        let dateTuple = (day , time)
        
        let response = CheckCar.Something.Response(dayTime: dateTuple)
        presenter?.presentReceiverDayTimeInspection(response: response)
    }
    
   
    
}
