//
//  SearchByModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 3/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchBy
{
  // MARK: Use cases
    enum TYPE : Int {
        case REGISTRATION_CAR
        case VIN
        case ENGINE_NUMBER

        
        var model : (Int, String, String) {
            switch self {
            case .REGISTRATION_CAR:
                return (0, "ทะเบียนรถ", "registration")
            case .VIN:
                return (1, "VIN", "vin")
            case .ENGINE_NUMBER:
                return (2, "หมายเลขเครื่องยนต์", "engineno")

            }
        }
    }
  enum Picker
  {
    struct Request
    {
        var selectRow : Int?
    }
    struct Response
    {
        var searchByList : [String]?
        var selectSearchByName : TYPE?
    }
    struct ViewModel
    {
        var searchByList : [String]?
        var selectSearchByName : TYPE?
    }
  }
}
