//
//  PlaceModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 2/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Place
{
  // MARK: Use cases
  
    
  enum Picker
  {
    struct Request
    {
        var filterName : String?
        var selectReceiveRow : PlantResponse?
        var selectStoreRow : StorageLocationModel?
    }
    struct Response
    {
        var plantLocationList : [PlantResponse]?
        var locationList : [StorageLocationModel]?
        var selectReceiveName : PlantResponse?
        var selectStoreName : StorageLocationModel?
        var selectReceiveValue : Int?
        var selectStoreValue : Int?
    }
    struct ViewModel
    {
        var plantLocationList : [PlantResponse]?
        var locationList : [StorageLocationModel]?
        var selectReceiveName : PlantResponse?
        var selectStoreName : StorageLocationModel?
        var selectReceiveValue : Int?
        var selectStoreValue : Int?
    }
  }
}
