//
//  LoginWorker.swift
//  Inspection
//
//  Created by Thanawat prathumset on 1/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias loginHandler = (Login.getLogin.Response) -> ()

class LoginWorker
{

    func login(username: String , password: String, completion: @escaping loginHandler){
        
        showLoading()
        
        let request = LoginRequest(username: username, password: password)
        LoginService().callServiceObject(request: request) { (results) in
            
            hideLoading()
            
            switch results {
            
            case .success(let loginResponse):
                let response = Login.getLogin.Response(loginResponse: loginResponse)
                completion(response)
                
            case .failure(let error):
                let response = Login.getLogin.Response(error: error.getMessage)
                completion(response)
            }
        }
    }
    
    
}
