//
//  EngineCarPresenter.swift
//  Inspection
//
//  Created by Thanawat prathumset on 8/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EngineCarPresentationLogic
{
    func presentSomething(response: EngineCar.Something.Response)
    func presentFuelDeliveryList(response: EngineCar.Something.Response)
    
}

class EngineCarPresenter: EngineCarPresentationLogic
{
  weak var viewController: EngineCarDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EngineCar.Something.Response)
  {
    let viewModel = EngineCar.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func presentFuelDeliveryList(response: EngineCar.Something.Response) {
        if let kError = response.error {
            let message = kError.message
            let viewModel = EngineCar.Something.ViewModel(errorMessage: message)
            viewController?.displayFuelDeliveryListError(viewModel: viewModel)
        }else{
            guard let result = response.fuelDeliveryList else { return }
            var values = result.map({ ("\($0.desc_LO ?? "")") })
            
            if !DataController.shared.isThaiLanguage() {
                values = result.map({ ("\($0.desc_BU ?? "")") })
            }
            
//            values = values.sorted(by: { $0 < $1 })
            let viewModel = EngineCar.Something.ViewModel(fuelDeliveryList: values)
            viewController?.displayFuelDeliveryList(viewModel: viewModel)
        }
    }
}
