//
//  RepoCarViewController.swift
//  Inspection
//
//  Created by Thanawat prathumset on 4/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RepoCarDisplayLogic: AnyObject
{
    func displaySomething(viewModel: RepoCar.Something.ViewModel)
    func displayDeliveryPersonDropdown(viewModel: RepoCar.Something.ViewModel)
    func displayReceiverDayTimeInspection(viewModel: RepoCar.Something.ViewModel)
    func displayDataDateTimeInspection(viewModel: RepoCar.Something.ViewModel)
    func displayWarehouseTimeInspection(viewModel: RepoCar.Something.ViewModel)
    func displayErrorSendRepo(viewModel: RepoCar.Something.ViewModel)
    func displaySuccessSendRepo(viewModel: RepoCar.Something.ViewModel)
}

class RepoCarViewController: UIViewController, RepoCarDisplayLogic
{
    // MARK: Do something
    @IBOutlet weak var fullName:UILabel!
    @IBOutlet weak var pickUpStackView: UIView!
    @IBOutlet weak var checkStackView: UIView!
    @IBOutlet weak var photoStackView: UIView!
    @IBOutlet weak var repoStackView: UIView!
    @IBOutlet weak var dateTimeView: UIView!
    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var timeLabel: UILabel!
    @IBOutlet weak var deliveryPersonTextField: DropDown!
    @IBOutlet weak var dataDateLabel: UILabel!
    @IBOutlet weak var warehouseDateLabel: UILabel!
    @IBOutlet weak var oldBuyerTextField:CustomTextField!
    @IBOutlet weak var deliveryTextField:CustomTextField!

    var isFetchList = false

    var sourceSectionName : [(name:String, cb: CheckBoxUIButton)] = []
    var interactor: RepoCarBusinessLogic?
    var router: (NSObjectProtocol & RepoCarRoutingLogic & RepoCarDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = RepoCarInteractor()
        let presenter = RepoCarPresenter()
        let router = RepoCarRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
            
            if let dateTimePicker = segue.destination as? DateTimeViewController {
                dateTimePicker.didSelectedDateTimePicker = { [weak self] (dateInspection) in
                    
                    let request = RepoCar.Something.Request(dateInspection: dateInspection)
                    if scene == "showDataDateTime" {
                        self?.interactor?.setDataDateTimeInspection(request: request)
                    } else if scene == "showWarehouseDateTime" {
                        self?.interactor?.setWarehouseDateTimeInspection(request: request)
                    } else {
                        self?.interactor?.setReceiverDateTimeInspection(request: request)
                    }
                }
            }
        }
    }
    
    // MARK: View lifecycle
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setTitleName()
        setUpTextField()
        setUpTab()
        setUpDateTime()
        doSomething()
        fetchDeliveryList()
    }
    
    func doSomething()
    {
        let request = RepoCar.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: RepoCar.Something.ViewModel) {
        
    }
    
    func displayDeliveryPersonDropdown(viewModel: RepoCar.Something.ViewModel) {
        guard let list = viewModel.deliveryCodes else { return }

        setValue(to: deliveryPersonTextField, values: list) { [weak self] (selectValue, _, _)  in
//            DataController.shared.receiverCarModel.receiverPlace = selectValue
            self?.deliveryPersonTextField.text = selectValue
            let request = RepoCar.Something.Request(deliveryPerson: selectValue)
            self?.interactor?.selectDelivery(request: request)
        }
        
        isFetchList = true
    }
    
    func setValue(to textfield:DropDown , values: [String], didSelected:@escaping (_ selectedText: String, _ index: Int , _ id:Int )->() ){
        textfield.optionArray = values
        textfield.didSelect(completion: didSelected)
    }
    
    //MARK: DateTime
    func setUpDateTime(){
        dateTimeView.isUserInteractionEnabled = true
        dateTimeView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(showDateTime)))
    }
    
    func displayReceiverDayTimeInspection(viewModel: RepoCar.Something.ViewModel) {
        guard let dayTime = viewModel.dayTime else { return }
        self.dateLabel.text = dayTime.day
        self.timeLabel.text = dayTime.time
    }
    
    func displayDataDateTimeInspection(viewModel: RepoCar.Something.ViewModel) {
        guard let dayTime = viewModel.dayTime else { return }
        self.dataDateLabel.text = dayTime.day
    }
    
    func displayWarehouseTimeInspection(viewModel: RepoCar.Something.ViewModel) {
        guard let dayTime = viewModel.dayTime else { return }
        self.warehouseDateLabel.text = dayTime.day
    }
    
    @objc func showDateTime(){
        performSegue(withIdentifier: "showDateTime", sender: nil)
    }
    
    @IBAction func toRootView(_ sender: Any) {
        popToRootViewController(confirm: true)
    }
    
    
    @IBAction func sendRepo(_ sender: UIButton) {
        print("🔶 send repo ")
        alert(message: "คุณต้องการส่ง\nsend repo ไหม") { [weak self] in
            self?.sendToRepo()
        }
    }
    
    func sendToRepo(){
        let request = RepoCar.Something.Request()
        interactor?.confirmSendToRepo(request: request)
    }
    
    func displayErrorSendRepo(viewModel: RepoCar.Something.ViewModel) {
        guard let errorMessage = viewModel.errorMessage else { return }
        alertErrorMessage(message: errorMessage) { [weak self] in
        }
    }
    
    func displaySuccessSendRepo(viewModel: RepoCar.Something.ViewModel) {
        print("🔶 repo displaySendRepoSuccess")
        //self.updateVehicleId()
        alertErrorMessageOKAction(message: "Repo สำเร็จ") {
            //ignored
        }
    }

    func validateInspectionIMAT(){
//        let request = PhotoCar.Something.Request()
//        interactor?.validateActionSendToInspectionIMAT(request: request)
    }
    
    func displayActionEventSuccess(viewModel: PhotoCar.Something.ViewModel) {
        
    }
    
    func displayUploadProgress(viewModel: PhotoCar.Something.ViewModel) {
        performSegue(withIdentifier: "UploadProgress", sender: nil)
    }
    
    func displayAlertMessage(viewModel: PhotoCar.Something.ViewModel) {
        guard let message = viewModel.alertPhotoMessage else { return }
        alertErrorMessageOKAction(message: message) {
            // ignored
        }
    }
    
    //MARK: SetupTab
    func setUpTab(){
        fullName.text = "ผู้ตรวจสภาพ \(DataController.shared.getFullName())"
        
        pickUpStackView.isUserInteractionEnabled = true
        pickUpStackView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(toPickUpCar)))
        
        checkStackView.isUserInteractionEnabled = true
        checkStackView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(toCheckCar)))
        
        photoStackView.isUserInteractionEnabled = true
        photoStackView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(toPhotoCar)))
        
        repoStackView.isUserInteractionEnabled = true
        repoStackView.addGestureRecognizer(UITapGestureRecognizer(target: self, action: #selector(toRepoCar)))
    }
    
    func setUpTextField(){
        oldBuyerTextField.autocorrectionType = .no
        deliveryTextField.autocorrectionType = .no

        oldBuyerTextField.delegate = self
        deliveryTextField.delegate = self
        
        addTarget(from: oldBuyerTextField)
        addTarget(from: deliveryTextField)
        
    }
    
    //MARK: Title
    func setTitleName(){
        title = "Repo"
    }
    
    func prepareData(){
//        let request = PhotoCar.Something.Request()
//        interactor?.prepareDataSection(request: request)
    }
    func fetchDeliveryList(){
        let request = RepoCar.Something.Request()
        interactor?.fetchDeliveryList(request: request)
    }
    
    func displayErrorFetchList(viewModel: RepoCar.Something.ViewModel) {
        guard let errorMessage = viewModel.errorMessage else { return }
        
        DispatchQueue.main.async { [weak self] in
            self?.alertErrorMessage(message: errorMessage) { [weak self] in
                self?.fetchDeliveryList()
            }
        }
        
    }
    func displayErrorDelete(viewModel: PhotoCar.Something.ViewModel) {
        guard let errorMessage = viewModel.errorMessage else { return }
        
        DispatchQueue.main.async { [weak self] in
            self?.alertErrorMessageOKAction(message: errorMessage) {
                // ignored
            }
        }
    }

    fileprivate func addTarget(from textfield: UITextField ){
        textfield.addTarget(self, action: #selector(textFieldDidChange(_:)),for: .editingChanged)
    }
}

//MARK: ViewController Lift Cycle
extension RepoCarViewController {
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        let dateInspection = DataController.shared.inspectionCarModel.date
        let request = RepoCar.Something.Request(dateInspection: dateInspection)
        interactor?.setReceiverDateTimeInspection(request: request)
                
        prepareData()
        validateInspectionIMAT()
    }
}

extension RepoCarViewController  {
    @objc func toPickUpCar() {
        navigationController?.popToViewController(withType: PickUpCarViewController.self, animated: false)
    }
    
    @objc func toCheckCar() {
        guard let nav = navigationController else { return }
        let foundCheckCar = nav.viewControllers.filter({ $0 is CheckCarViewController})
        if foundCheckCar.count > 0 {
            navigationController?.popViewController(animated: false)
        }else{
            navigationController?.pushViewController(CarInspectionPage.CHECK_CAR.VC,  animated: false)
        }
    }
    
    @objc func toPhotoCar() {
        guard let nav = navigationController else { return }
        let foundPhotoCar = nav.viewControllers.filter({ $0 is PhotoCarViewController})
        if foundPhotoCar.count > 0 {
            navigationController?.popViewController(animated: false)
        }else{
            navigationController?.pushViewController(CarInspectionPage.PHOTO_CAR.VC, animated: false)
        }
        
    }
    
    @objc func toRepoCar() {
    }
}

extension RepoCarViewController : UITextFieldDelegate {
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
}

extension  RepoCarViewController {
    @objc func textFieldDidChange(_ textField: UITextField) {
        //print(textField.text)
        switch textField {
        case oldBuyerTextField:
            interactor?.fillOldBuyer(request: RepoCar.Something.Request(oldBuyer: textField.text))
        case deliveryTextField:
            interactor?.fillDelivery(request: RepoCar.Something.Request(deliveryInputText: textField.text))
        default:
            break
        }
    }
    
}

