//
//  AirCheckInteractor.swift
//  Inspection
//
//  Created by Thanawat prathumset on 15/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AirCheckBusinessLogic
{
  func doSomething(request: AirCheck.Something.Request)
}

protocol AirCheckDataStore
{
  //var name: String { get set }
}

class AirCheckInteractor: AirCheckBusinessLogic, AirCheckDataStore
{
  var presenter: AirCheckPresentationLogic?
  var worker: AirCheckWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AirCheck.Something.Request)
  {
    worker = AirCheckWorker()
    worker?.doSomeWork()
    
    let response = AirCheck.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
