//
//  AirCheckViewController.swift
//  Inspection
//
//  Created by Thanawat prathumset on 15/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RadioGroup

protocol AirCheckDisplayLogic: AnyObject
{
    func displaySomething(viewModel: AirCheck.Something.ViewModel)
}

class AirCheckViewController: ViewController, AirCheckDisplayLogic
{
    var interactor: AirCheckBusinessLogic?
    var router: (NSObjectProtocol & AirCheckRoutingLogic & AirCheckDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = AirCheckInteractor()
        let presenter = AirCheckPresenter()
        let router = AirCheckRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setUIView()
        setRadio()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var summaryAirSystemTextField: MultilineTextField!
    @IBOutlet weak var compresserCheckBox: CheckBoxUIButton!
    @IBOutlet weak var airSystemRadio: RadioGroup!
    
    // local strings
    @IBOutlet weak var airSystemLabel: UILabel!
    @IBOutlet weak var compresserLabel: UILabel!
    @IBOutlet weak var summaryLabel: UILabel!
    
    let strings_inspection_air_cool = String.localized("inspection_air_cool_label")
    let strings_inspection_air_not_cool = String.localized("inspection_air_not_cool_label")


    override func initLocalString() {
        super.initLocalString()
        
        airSystemLabel.text = String.localized("inspection_air_system_label")
        compresserLabel.text = String.localized("inspection_air_compressor_label")
        summaryLabel.text = String.localized("inspection_air_summary_label")
        summaryAirSystemTextField.placeholder = summaryLabel.text
    }
    
    func doSomething()
    {
        let request = AirCheck.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: AirCheck.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    
    //MARK: UIView
    func setUIView(){
        summaryAirSystemTextField.autocorrectionType = .no
        summaryAirSystemTextField.delegate = self
        
    }
    
    @IBAction func compresserTapped(_ sender: Any) {
        compresserCheckBox.toggle { check in
            DataController.shared.inspectionCarModel.isCompresser = check
        }
    }
    
    
    //MARK: Radio
    func setRadio(){
        let attributedString = [NSAttributedString.Key.foregroundColor : UIColor.appPrimaryColor]
        
        airSystemRadio.attributedTitles = [
            NSAttributedString(
                string: strings_inspection_air_cool, attributes: attributedString),
            NSAttributedString(
                string: strings_inspection_air_not_cool, attributes: attributedString)
        ]
    }
    
    @IBAction func airSystemValueChanged(_ sender: Any) {
        let value = getRadioValue(from: [strings_inspection_air_cool, strings_inspection_air_not_cool], selectIndex: airSystemRadio.selectedIndex)
        DataController.shared.inspectionCarModel.airSystem = value
        
        let isAirCool = airSystemRadio.selectedIndex == 0 ? true : false
        DataController.shared.inspectionCarModel.isAirCool = isAirCool
    }
    
    func prepareData(){
        let model = DataController.shared.inspectionCarModel
        summaryAirSystemTextField.text = model.summaryAirSystem
        compresserCheckBox.check = model.isCompresser
        airSystemRadio.selectedIndex = getRadioIndexByValue(from: [strings_inspection_air_cool, strings_inspection_air_not_cool], value: model.airSystem)
    }
}



//MARK: TextView Delegate
extension AirCheckViewController : UITextViewDelegate {
    func textViewDidChange(_ textView: UITextView) {
        //print(textView.text)
        DataController.shared.inspectionCarModel.summaryAirSystem = textView.text
    }
}


extension AirCheckViewController {
    
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        scrollView.registKeyboardNotification()
        
        prepareData()
        
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        scrollView.resignKeyboardNotification()
    }
}
