//
//  MotorcycleCheckPresenter.swift
//  Inspection
//
//  Created by Thanawat Pratumsat on 20/9/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MotorcycleCheckPresentationLogic
{
  func presentSomething(response: MotorcycleCheck.Something.Response)
    func presentProvinceList(response: MotorcycleCheck.Something.Response)
    
    func presentRearTreadDepthDecimal(response: MotorcycleCheck.Something.Response)
    func presentFrontTreadDepthDecimal(response: MotorcycleCheck.Something.Response)
}

class MotorcycleCheckPresenter: MotorcycleCheckPresentationLogic
{
  weak var viewController: MotorcycleCheckDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MotorcycleCheck.Something.Response)
  {
    let viewModel = MotorcycleCheck.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func presentProvinceList(response: MotorcycleCheck.Something.Response) {
        if let kError = response.error {
            let message = kError.message
            let viewModel = MotorcycleCheck.Something.ViewModel(errorMessage: message)
            viewController?.displayShowProvinceError(viewModel: viewModel)
        }else{
            guard let provinceList = response.provinceList else { return }
            var values = provinceList.map({ $0.desc_LO ?? "" })
//            if !DataController.shared.isThaiLanguage() {
//                values = provinceList.map({ $0.desc_BU ?? "" })
//            }
            let viewModel = MotorcycleCheck.Something.ViewModel(provinceList: values)
            viewController?.displayProvinceDropdown(viewModel: viewModel)
        }
    }
    
    
    
    func presentRearTreadDepthDecimal(response: MotorcycleCheck.Something.Response) {
        let viewModel = MotorcycleCheck.Something.ViewModel(rearTreadDepthValidNumber: response.decimalNumber)
        viewController?.displayRearTreadDepthValidNumber(viewModel: viewModel)
    }
    func presentFrontTreadDepthDecimal(response: MotorcycleCheck.Something.Response) {
        let viewModel = MotorcycleCheck.Something.ViewModel(frontTreadDepthValidNumber: response.decimalNumber)
        viewController?.displayFrontTreadDepthValidNumber(viewModel: viewModel)
    }
}
