//
//  GradeCarModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 11/3/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum GradeCar
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        // exellence
        var e1Chehck : Bool?
        var e2Chehck : Bool?
        var e3Chehck : Bool?
        var e4Chehck : Bool?
        var e5Chehck : Bool?
        
        // good
        var g1Chehck : Bool?
        var g2Chehck : Bool?
        var g3Chehck : Bool?
        var g4Chehck : Bool?
        
        // average
        var a1Chehck : Bool?
        var a2Chehck : Bool?
        var a3Chehck : Bool?
        var a4Chehck : Bool?
        
        // fair
        var f1Chehck : Bool?
        var f2Chehck : Bool?
        var f3Chehck : Bool?
        var f4Chehck : Bool?
        var f5Chehck : Bool?
        var f6Chehck : Bool?
        var f7Chehck : Bool?
        var f8Chehck : Bool?
        var f9Chehck : Bool?
        var f10Chehck :Bool?
        var f11Chehck :Bool?
        
        // poor
        var p1Chehck : Bool?
        var p2Chehck : Bool?
        var p3Chehck : Bool?
        var p4Chehck : Bool?
        var p5Chehck : Bool?
        var p6Chehck : Bool?
        var p7Chehck : Bool?
        var p8Chehck : Bool?
        var p9Chehck : Bool?
        
        // x
        var x1Chehck : Bool?
        
        // y
        var y1Chehck : Bool?
    }
    struct Response
    {
        var grade: String?
    }
    struct ViewModel
    {
        var grade: String?
    }
  }
}
