//
//  CreateModelCodeModels.swift
//  Inspection
//
//  Created by Thanawat Pratumsat on 23/6/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateModelCode
{
  // MARK: Use cases
    enum ModelCodeType {
        case CREATE
        case UPDATE
    }
  enum Something
  {
    struct Request
    {
        var makeValue:String?
        var bodyValue:String?
        var driveValue:String?
        var gearValue:String?
        var gearBoxValue:String?
        var fuelTypeValue:String?
        var fuelDeliveryValue:String?
        
        var model_Bu:String?
        var model_Lo:String?
        var varaints:String?
        var modelCode:String?
        var engineCapacity:String?
        var buildYear:String?
        var chassisno:String?
        
        var modelCodeType: ModelCodeType?
    }
    struct Response
    {
        var makeList: [StandradMakeModel]?
        var bodyList: [BodyCarModel]?
        var driveList: [DriveModel]?
        var gearList: [String]?//what the value?
        var gearBoxList: [GearBoxModel]?
        var fuelTypeList: [FuelTypeModel]?
        var fuelDeliveryList: [FuelDeliveryModel]?
        var mottoModelCode: String?
        var buildYearList: [String]?
        var validateErrorMessage:String?
        
        var jatoCarModelList:[JatoCarModelsModel]?
        var jatoVaraintsList:[JatoVaraintsModel]?
        var model_Lo:String?
        var modelCodeType: ModelCodeType?
        var error : KErrorMessage?
        
        var modelCodeTemplate: ModelCodeTemplateModel?
        var editMake:String?
        var editBody:String?
        var editFuelDelivery:String?
        var editFuelType:String?
        var editGearBox:String?
        var editDrive:String?
    }
    struct ViewModel
    {
        var makeList_bu: [String]?
        var bodyList_bu: [String]?
        var driveList_bu: [String]?
        var gearList_bu: [String]?
        var gearBoxList_bu: [String]?
        var fuelTypeList_bu: [String]?
        var fuelDeliveryList_bu: [String]?
        var mottoModelCode: String?
        var buildYearList: [String]?
        var message: String?
        
        
        var jatoCarModelList_bu:[String]?
        var jatoVaraintsList_bu:[String]?
        var model_Lo: String?
        var modelCodeType: ModelCodeType?
        var errorMessage : String?
        
        var modelCodeTemplate: ModelCodeTemplateModel?
        var editMake:String?
        var editBody:String?
        var editFuelDelivery:String?
        var editFuelType:String?
        var editGearBox:String?
        var editDrive:String?
    }
  }
}
