//
//  ReceiverCarRouter.swift
//  Inspection
//
//  Created by Thanawat prathumset on 8/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ReceiverCarRoutingLogic
{
  func routeTosignatureSegue(segue: UIStoryboardSegue?)
}

protocol ReceiverCarDataPassing
{
  var dataStore: ReceiverCarDataStore? { get }
}

class ReceiverCarRouter: NSObject, ReceiverCarRoutingLogic, ReceiverCarDataPassing
{
  weak var viewController: ReceiverCarViewController?
  var dataStore: ReceiverCarDataStore?
  
  // MARK: Routing
  
  func routeTosignatureSegue(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! SignatureViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "PickUpCar", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "SignatureViewController") as! SignatureViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: ReceiverCarViewController, destination: SignatureViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: ReceiverCarDataStore, destination: inout SignatureDataStore)
  {
    destination.title = source.title
    destination.signatureImage = source.signatureImage
    destination.user = source.user
  }
}
