//
//  CabinCarModels.swift
//  Inspection
//
//  Created by Thanawat prathumset on 8/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CabinCar
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var miles : String?
        
        var keyCheck: String?
        var remoteCheck: String?
        var remoteKeyCheck: String?
        var immobilizerKeyCheck: String?
        var keylessKeyCheck: String?
        
        var brandPlayer: String?
        
        var dateExpired: Date?
        
        var selectGearbox:String?
        
        var codeGearBox:String?
        
    }
    struct Response
    {
        var validateMilesNumber: String?
        var isKeyCheck: Bool?
        var isRemoteCheck: Bool?
        var isRemoteKeyCheck: Bool?
        var isImmobilizerKeyCheck: Bool?
        var isKeylessKeyCheck: Bool?
        
        var isPlayerCheckBox: Bool?
        
        var dayTime: (day:String, time:String)?
       
        var gearBoxList:[GearBoxModel]?
        var error: KErrorMessage?
        
        var gearBox_BU:String?
    }
    struct ViewModel
    {
        var validateMilesNumber: String?
        var isKeyCheck: Bool?
        var isRemoteCheck: Bool?
        var isRemoteKeyCheck: Bool?
        var isImmobilizerKeyCheck: Bool?
        var isKeylessKeyCheck: Bool?
        
        var isPlayerCheckBox: Bool?
        
        var dayTime: (day:String, time:String)?
        
        var gearBoxList_bu:[String]?
        
        var gearBox_BU:String?
        
        var errorMessage:String?
    }
  }
}
