//
//  PDFPreviewInteractor.swift
//  Inspection
//
//  Created by Thanawat prathumset on 19/2/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol PDFPreviewBusinessLogic
{
  func previewPDFGenerate(request: PDFPreview.Something.Request)
    func printPDF(request: PDFPreview.Something.Request)
}

protocol PDFPreviewDataStore
{
  //var name: String { get set }
    var documentData : Data? { get set }
    var pdfName : String? { get set }
}

class PDFPreviewInteractor: PDFPreviewBusinessLogic, PDFPreviewDataStore
{
  var presenter: PDFPreviewPresentationLogic?
  var worker: PDFPreviewWorker?
    
    var documentData : Data?
    var pdfName : String?
  // MARK: Do something
  
  func previewPDFGenerate(request: PDFPreview.Something.Request)
  {
    let response = PDFPreview.Something.Response(documentData: documentData)
    presenter?.presentPDFViewer(response: response)
  }
    func printPDF(request: PDFPreview.Something.Request) {
        let response = PDFPreview.Something.Response(documentData: documentData,
                                                     pdfName: pdfName)
        presenter?.presentPrint(response: response)
    }
}
