//
//  ImageViewerModels.swift
//  Inspection
//
//  Created by Thanawat Pratumsat on 4/8/2564 BE.
//  Copyright (c) 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImageViewer
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var image:UIImage?
    }
    struct ViewModel
    {
        var image:UIImage?
    }
  }
}
